/**
 * @file concat.h
 * @brief Concat the BaseVar VCF and CVG files.
 * 
 * @author Shujia Huang
 * @date 2018-09-14
 * 
 */

#ifndef __INCLUDE_BASEVAR_CONCAT_H__
#define __INCLUDE_BASEVAR_CONCAT_H__

#include <iostream>
#include <fstream>
#include <string>
#include <vector>

#include <getopt.h>
#include <htslib/bgzf.h>
#include <htslib/kstring.h>

#include "basetype_utils.h"
#include "utils.h"

static const std::string __CONCAT_USAGE = 
    "About: Concatenate or combine BaseVar's VCF/CVG files.\n" 
    "Usage: basevar concat [options] <-I input> | <-L input_filelist> <-O outputfile> ...\n\n"
    "CAUTION: This function does not sort the postions, user should take care the concat order by themself.\n" 
    "optional arguments:\n" 
    "  -I, --input=FILE       VCF/CVG file generated by BaseVar.\n"
    "  -L, --file-list=FILE   VCF/CVG files list, one file per row.\n"
    "  -O, --output=FILE      Write output to a file.\n"
    "  -h, --help             Show this help message and exit.";

static const struct option CONCAT_CMDLINE_LOPTS[] = {
    {"input",           optional_argument, NULL, 'I'},
    {"align-file-list", optional_argument, NULL, 'L'},
    {"output",          required_argument, NULL, 'O'},
    {"help",                  no_argument, NULL, 'h'},

    // must set this value
    {0, 0, 0, 0}
};

int concat_runner(int argc, char *argv[]);

#endif